version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: ${APP_NAME}_nginx

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    container_name: ${APP_NAME}_app

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8101:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: ${APP_NAME}_mysql

  phpmyadmin:
    image: phpmyadmin
    links:
      - mysql:mysql
    ports:
      - "8080:80"
    environment:
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      PMA_HOST: mysql
    depends_on:
      - mysql
    container_name: ${APP_NAME}_phpmyadmin
